
FROM node:20-alpine AS builder

WORKDIR /app


COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .



RUN npm run build  --verbose


FROM nginx:alpine AS production 

EXPOSE 80


RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=builder /app/dist /usr/share/nginx/html


CMD ["nginx", "-g", "daemon off;"]